# Generated by Django 5.2.5 on 2025-10-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPPFrameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt', models.BooleanField(default=False)),
                ('Drogon', models.BooleanField(default=False)),
                ('Cocos2dx', models.BooleanField(default=False)),
                ('Boost', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gin', models.BooleanField(default=False)),
                ('Echo', models.BooleanField(default=False)),
                ('Fiber', models.BooleanField(default=False)),
                ('Beego', models.BooleanField(default=False)),
                ('Revel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JavaFrameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spring', models.BooleanField(default=False)),
                ('JavaServerFaces', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JavaScriptFrameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('React', models.BooleanField(default=False)),
                ('NextJs', models.BooleanField(default=False)),
                ('Angular', models.BooleanField(default=False)),
                ('Vue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='media/user_avatar')),
                ('aboutme', models.TextField(blank=True)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Python', models.BooleanField(default=False)),
                ('JavaScript', models.BooleanField(default=False)),
                ('CPP', models.BooleanField(default=False)),
                ('GoLang', models.BooleanField(default=False)),
                ('Java', models.BooleanField(default=False)),
                ('CSharp', models.BooleanField(default=False)),
                ('C', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PythonFrameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Django', models.BooleanField(default=False)),
                ('Flask', models.BooleanField(default=False)),
                ('CherryPy', models.BooleanField(default=False)),
                ('WebPy', models.BooleanField(default=False)),
            ],
        ),
    ]
