# Generated by Django 5.2.5 on 2025-10-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSearchApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CPPFrameworks',
        ),
        migrations.DeleteModel(
            name='GoLang',
        ),
        migrations.DeleteModel(
            name='JavaFrameworks',
        ),
        migrations.DeleteModel(
            name='JavaScriptFrameworks',
        ),
        migrations.DeleteModel(
            name='ProgramLanguages',
        ),
        migrations.DeleteModel(
            name='PythonFrameworks',
        ),
    ]
