# Generated by Django 5.2.5 on 2025-10-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSearchApp', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stack',
            field=models.CharField(default='python', max_length=40),
        ),
    ]
