# Generated by Django 5.2.5 on 2025-10-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSearchApp', '0004_post_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
