# Generated by Django 5.2.7 on 2025-10-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSearchApp', '0005_alter_profilepage_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/post_image'),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
