# Generated by Django 5.2.7 on 2025-10-31 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSearchApp', '0008_remove_post_code_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
