# Generated by Django 5.2.5 on 2025-11-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSearchApp', '0010_alter_profilepage_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
