# Generated by Django 5.2.7 on 2025-11-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSearchApp', '0012_savepost_postsaved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsaved',
            old_name='posts',
            new_name='get_user',
        ),
        migrations.RenameField(
            model_name='savepost',
            old_name='post',
            new_name='user',
        ),
    ]
