# Generated by Django 5.2.7 on 2025-11-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSearchApp', '0013_rename_posts_postsaved_get_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsaved',
            name='post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='CodeSearchApp.post'),
            preserve_default=False,
        ),
    ]
