# Generated by Django 5.2.5 on 2026-02-17 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSearchApp', '0014_postsaved_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savepost',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PostSaved',
        ),
        migrations.DeleteModel(
            name='SavePost',
        ),
    ]
